'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddResidents
    
    '''<summary>
    '''SelectApartmentNumberPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectApartmentNumberPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ResidentsApartmentNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentsApartmentNumberLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ResidentAppartmentNumberListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentAppartmentNumberListBox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''ResidentsApartmentNumberLabelMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentsApartmentNumberLabelMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AddResidentForApartmentChosenButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddResidentForApartmentChosenButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''AddResidentsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddResidentsPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PrimaryLeaserLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrimaryLeaserLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ResidentCalendarErrofLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentCalendarErrofLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateResidentAddedCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateResidentAddedCalendar As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''ResidentLastNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentLastNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ResidentLastNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentLastNameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ResidentLastNameErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentLastNameErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ResidentFirstNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentFirstNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ResidentFirstNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentFirstNameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ResidentFirstNameErrorLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentFirstNameErrorLable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SignedLeaseDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignedLeaseDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SignedLeaseDropDownListErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignedLeaseDropDownListErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AddResidentButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddResidentButton As Global.System.Web.UI.WebControls.Button
End Class
