'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class About
    
    '''<summary>
    '''CalendarErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateSignedCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateSignedCalendar As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''ApartmentNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApartmentNumberLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AppartmentNumberListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AppartmentNumberListBox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''ApartmnetFullLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApartmnetFullLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CurrentRateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentRateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CurrentRateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentRateTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RateErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RateErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LastNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastNameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LastNameErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastNameErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FirstNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstNameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FirstNameErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstNameErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CreateContractButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateContractButton As Global.System.Web.UI.WebControls.Button
End Class
