'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Rents
    
    '''<summary>
    '''ChooseApartmentNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChooseApartmentNumber As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ResidentAppartmentNumberListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentAppartmentNumberListBox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''ResidentsApartmentNumberLabelMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResidentsApartmentNumberLabelMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ManageRents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManageRents As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ChangeApartmentNumberButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangeApartmentNumberButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ApartmentChosenLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApartmentChosenLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TransactionTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionTable As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''Cell0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell0 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TransactionChoiceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionChoiceDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TransactionChoiceDropErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionChoiceDropErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''InputDataPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InputDataPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescriptionLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DescriptionTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescriptionTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DescriptionTextBoxErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescriptionTextBoxErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DateTextBoxErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateTextBoxErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EnterAmountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnterAmountLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AmountTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AmountErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PaymentTypeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentTypeDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SaveTransactionButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveTransactionButton As Global.System.Web.UI.WebControls.Button
End Class
